//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Programma_7
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Сенсоры.
    /// </summary>
    // *** Start programmer edit section *** (Сенсоры CustomAttributes)

    // *** End programmer edit section *** (Сенсоры CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СенсорыE", new string[] {
            "Тип as \'Тип\'",
            "IdДатчки as \'Id датчки\'"})]
    [View("СенсорыL", new string[] {
            "Тип as \'Тип\'",
            "IdДатчки as \'Id датчки\'"})]
    public class Сенсоры : ICSSoft.STORMNET.DataObject
    {
        
        private string fТип;
        
        private int fIdДатчки;
        
        // *** Start programmer edit section *** (Сенсоры CustomMembers)

        // *** End programmer edit section *** (Сенсоры CustomMembers)

        
        /// <summary>
        /// IdДатчки.
        /// </summary>
        // *** Start programmer edit section *** (Сенсоры.IdДатчки CustomAttributes)

        // *** End programmer edit section *** (Сенсоры.IdДатчки CustomAttributes)
        public virtual int IdДатчки
        {
            get
            {
                // *** Start programmer edit section *** (Сенсоры.IdДатчки Get start)

                // *** End programmer edit section *** (Сенсоры.IdДатчки Get start)
                int result = this.fIdДатчки;
                // *** Start programmer edit section *** (Сенсоры.IdДатчки Get end)

                // *** End programmer edit section *** (Сенсоры.IdДатчки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сенсоры.IdДатчки Set start)

                // *** End programmer edit section *** (Сенсоры.IdДатчки Set start)
                this.fIdДатчки = value;
                // *** Start programmer edit section *** (Сенсоры.IdДатчки Set end)

                // *** End programmer edit section *** (Сенсоры.IdДатчки Set end)
            }
        }
        
        /// <summary>
        /// Тип.
        /// </summary>
        // *** Start programmer edit section *** (Сенсоры.Тип CustomAttributes)

        // *** End programmer edit section *** (Сенсоры.Тип CustomAttributes)
        [StrLen(255)]
        public virtual string Тип
        {
            get
            {
                // *** Start programmer edit section *** (Сенсоры.Тип Get start)

                // *** End programmer edit section *** (Сенсоры.Тип Get start)
                string result = this.fТип;
                // *** Start programmer edit section *** (Сенсоры.Тип Get end)

                // *** End programmer edit section *** (Сенсоры.Тип Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сенсоры.Тип Set start)

                // *** End programmer edit section *** (Сенсоры.Тип Set start)
                this.fТип = value;
                // *** Start programmer edit section *** (Сенсоры.Тип Set end)

                // *** End programmer edit section *** (Сенсоры.Тип Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СенсорыE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СенсорыE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СенсорыE", typeof(IIS.Programma_7.Сенсоры));
                }
            }
            
            /// <summary>
            /// "СенсорыL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СенсорыL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СенсорыL", typeof(IIS.Programma_7.Сенсоры));
                }
            }
        }
    }
}
